version: '3.8'

networks:
  default:
    name: topaya

services:
  zookeeper:
    image: bitnami/zookeeper:3.8
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:3.5
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    ports:
      - "9092:9092"

  kafka-init:
    image: bitnami/kafka:3.5
    container_name: kafka-init
    depends_on:
      - kafka
    entrypoint: |
      bash -c "
        echo 'Esperando a que Kafka esté listo...';
        while ! /opt/bitnami/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --list; do
          sleep 5;
        done;
        echo 'Kafka está listo, creando tópicos...';
        /opt/bitnami/kafka/bin/kafka-topics.sh --create --topic topicopedidos --bootstrap-server kafka:9092 --partitions 10 --replication-factor 1;
        /opt/bitnami/kafka/bin/kafka-topics.sh --create --topic topicopedidos.reply --bootstrap-server kafka:9092 --partitions 10 --replication-factor 1;
        echo 'Tópicos creados. Finalizando.';
      "
